# Generated by Django 6.1 on 2026-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerprint_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='fingerprint_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
