# Generated by Django 6.1 on 2026-08-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_alter_department_head_of_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(auto_now_add=True, db_index=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('lateness_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
                ('officer', models.ForeignKey(blank=True, db_column='officer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_attendances', to='employees.officer')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'indexes': [models.Index(fields=['attendance_date', 'employee'], name='attendance_attenda_905d5f_idx'), models.Index(fields=['attendance_date', 'officer'], name='attendance_attenda_749d13_idx')],
            },
        ),
    ]
